# Extended Data Table 2

Environment: env1

In [ ]:
import pandas as pd
import os
import shutil
import numpy as np
import pickle
import sys

sys.path.append("/gpfs/data/shenhavlab/users/ca3261/Visionary_AI/src/analysis/final_figures/final_submission/")
from utils import get_bmi, proc_birth_hx, proc_on_yes, proc_on_no, proc_smoker, proc_db, proc_conception, compare_binary_col, compare_continuous_col

In [ ]:
participant_tracker = pd.read_csv('/gpfs/data/shenhavlab/PROJECTS/visionary_ai/data/clinical_data/Visionary AI Participant Tracker(FMF Algorithim )_052126.csv')
participant_tracker = participant_tracker[participant_tracker['Record ID']!='NYU130'] # stillbirth
participant_tracker = participant_tracker.drop(columns=[x for x in participant_tracker.columns if 'Unnamed' in x])

In [ ]:
nyu_pec = pd.read_pickle("/gpfs/data/shenhavlab/PROJECTS/visionary_ai/data/clinical_data/nyu_cases_051126.pkl")
nyu_controls = pd.read_pickle("/gpfs/data/shenhavlab/PROJECTS/visionary_ai/data/clinical_data/nyu_controls_051126.pkl")
nyu_ids = nyu_pec+nyu_controls

In [6]:
nyu_ghtn = ['nyu017', 'nyu019', 'nyu032', 'nyu039', 'nyu041', 'nyu069', 'nyu082', 'nyu054', 'nyu091', 'nyu102',
            'nyu115', 'nyu120', 'nyu138']

nyu_chtn = ['NYU044', 'NYU047', 'NYU021', 'NYU025', 'NYU026','NYU136']

nyu_ppec = ['nyu049']

nyu_gdm = ['nyu007', 'nyu015', 'nyu025', 'nyu078', 'nyu079', 'nyu080', 'nyu099']

nyu_fgr = ['nyu005', 'nyu079', 'nyu085', 'nyu136', 'nyu139']

nyu_chtn = [x.lower() for x in nyu_chtn]

In [7]:
nyu_md = participant_tracker.copy()
nyu_md =nyu_md.drop_duplicates()

nyu_md['Record ID'] = nyu_md['Record ID'].str.lower()
nyu_md = nyu_md[nyu_md['Record ID'].isin(nyu_ids)]



nyu_md = get_bmi(nyu_md, 'Weight (kg)', 'Height (m)')

nyu_md['obesity'] = nyu_md['bmi']>=30

nyu_md = proc_birth_hx(nyu_md, 'Pts last birth Dx (PEC/GDM, GHTN, Preterm)')
nyu_md = proc_on_yes(nyu_md, 'cHTN')
nyu_md = proc_smoker(nyu_md, 'Smoking Status ')
nyu_md = proc_db(nyu_md, 'Diabetes?')
nyu_md = proc_conception(nyu_md, 'Conception Method ')
nyu_md = proc_on_no(nyu_md, 'Nulliparity?')

In [9]:
nyu_md['Age '] = (
    nyu_md['Age ']
    .str.extract(r'(\d+)')[0]
    .astype(int)
)

In [10]:
nyu_sf = ['NYU001', 'NYU011', 'NYU021', 'NYU063', 'NYU085', 'NYU086','NYU088','NYU101','NYU025']
nyu_nsf = ['NYU034', 'NYU042', 'NYU070','NYU094','NYU096']

nyu_eope = ['nyu001',]
nyu_lope = ['nyu011','nyu021','nyu025','nyu034','nyu042','nyu088','nyu070','nyu101','nyu063','nyu094','nyu096','nyu085','nyu086']

nyu_sf = [x.lower() for x in nyu_sf]
nyu_nsf = [x.lower() for x in nyu_nsf]

In [11]:
pec_md = nyu_md[nyu_md['Record ID'].str.lower().isin(nyu_pec)]
controls_md = nyu_md[nyu_md['Record ID'].str.lower().isin(nyu_controls)]
sf_md = nyu_md[nyu_md['Record ID'].str.lower().isin(nyu_sf)]
nsf_md = nyu_md[nyu_md['Record ID'].str.lower().isin(nyu_nsf)]
eope_md = nyu_md[nyu_md['Record ID'].str.lower().isin(nyu_eope)]
lope_md = nyu_md[nyu_md['Record ID'].str.lower().isin(nyu_lope)]
ghtn_md = nyu_md[nyu_md['Record ID'].str.lower().isin(nyu_ghtn)]


controls_md = nyu_md[nyu_md['Record ID'].str.lower().isin(nyu_controls)]

In [12]:
compare_continuous_col(
    nyu_md=nyu_md,
    col='Age ',
    controls_ids=nyu_controls,
    group_ids={'cohort': nyu_ids,'pec':nyu_pec, 'sf':nyu_sf,'nsf':nyu_nsf,'eope':nyu_eope,'lope':nyu_lope,'ghtn':nyu_ghtn},
    id_col="Record ID"
)

=== Age  ===
controls: n=65, mean=34.631, median=34.000, sd=4.407
cohort: n=79, mean=34.709, median=35.000, sd=4.555, pval: 0.8625018046854372
pec: n=14, mean=35.071, median=36.000, sd=5.356, pval: 0.5797779199831079
sf: n=9, mean=34.778, median=36.000, sd=5.380, pval: 0.6128440844943841
nsf: n=5, mean=35.600, median=36.000, sd=5.899, pval: 0.7836501882573331
eope: n=1, mean=33.000, median=33.000, sd=nan, pval: 0.5801299553053225
lope: n=13, mean=35.231, median=36.000, sd=5.540, pval: 0.4677501219561734
ghtn: n=8, mean=35.500, median=36.500, sd=4.690, pval: 0.34770650460400754

    group   n       mean  median        sd  statistic    pvalue         test
0  cohort  79  34.708861    35.0  4.554941     2524.0  0.862502  mannwhitney
1     pec  14  35.071429    36.0  5.356007      411.5  0.579778  mannwhitney
2      sf   9  34.777778    36.0  5.380004      261.5  0.612844  mannwhitney
3     nsf   5  35.600000    36.0  5.899152      150.0  0.783650  mannwhitney
4    eope   1  33.000000    33.0       NaN       43.5  0.580130  mannwhitney
5    lope  13  35.230769    36.0  5.540064      368.0  0.467750  mannwhitney
6    ghtn   8  35.500000    36.5  4.690416      206.5  0.347707  mannwhitney

In [13]:
nyu_md['hispanic'] = (nyu_md['Ethnicity'].str.lower().str.contains('hispanic'))&(~nyu_md['Ethnicity'].str.lower().str.contains('not'))

compare_binary_col(
    nyu_md=nyu_md,
    col='hispanic',
    controls_ids=nyu_controls,
    group_ids={'cohort': nyu_ids,'pec':nyu_pec, 'sf':nyu_sf,'nsf':nyu_nsf,'eope':nyu_eope,'lope':nyu_lope,'ghtn':nyu_ghtn},
    id_col="Record ID"
)

=== hispanic ===
controls: 6/65 (0.092)
cohort: 7/79 (0.089) pval: 1.0
pec: 1/14 (0.071) pval: 1.0
sf: 0/9 (0.000) pval: 1.0
nsf: 1/5 (0.200) pval: 0.4192482137094121
eope: 0/1 (0.000) pval: 1.0
lope: 1/13 (0.077) pval: 1.0
ghtn: 0/8 (0.000) pval: 1.0

    group   n  count  proportion  odds_ratio    pvalue
0  cohort  79      7    0.088608    1.046005  1.000000
1     pec  14      1    0.071429    1.322034  1.000000
2      sf   9      0    0.000000         inf  1.000000
3     nsf   5      1    0.200000    0.406780  0.419248
4    eope   1      0    0.000000         inf  1.000000
5    lope  13      1    0.076923    1.220339  1.000000
6    ghtn   8      0    0.000000         inf  1.000000

In [14]:
compare_binary_col(
    nyu_md=nyu_md,
    col='obesity',
    controls_ids=nyu_controls,
    group_ids={'cohort': nyu_ids,'pec':nyu_pec, 'sf':nyu_sf,'nsf':nyu_nsf,'eope':nyu_eope,'lope':nyu_lope,'ghtn':nyu_ghtn},
    id_col="Record ID"
)

=== obesity ===
controls: 16/65 (0.246)
cohort: 21/79 (0.266) pval: 0.849360774365261
pec: 5/14 (0.357) pval: 0.5056162260655342
sf: 3/9 (0.333) pval: 0.6860356604822078
nsf: 2/5 (0.400) pval: 0.5973688867913414
eope: 0/1 (0.000) pval: 1.0
lope: 5/13 (0.385) pval: 0.31960483644106485
ghtn: 3/8 (0.375) pval: 0.4211216420203957

    group   n  count  proportion  odds_ratio    pvalue
0  cohort  79     21    0.265823    0.901846  0.849361
1     pec  14      5    0.357143    0.587755  0.505616
2      sf   9      3    0.333333    0.653061  0.686036
3     nsf   5      2    0.400000    0.489796  0.597369
4    eope   1      0    0.000000         inf  1.000000
5    lope  13      5    0.384615    0.522449  0.319605
6    ghtn   8      3    0.375000    0.544218  0.421122

In [15]:
compare_binary_col(
    nyu_md=nyu_md,
    col='Past Preeclampsia',
    controls_ids=nyu_controls,
    group_ids={'cohort': nyu_ids,'pec':nyu_pec, 'sf':nyu_sf,'nsf':nyu_nsf,'eope':nyu_eope,'lope':nyu_lope,'ghtn':nyu_ghtn},
    id_col="Record ID"
)

=== Past Preeclampsia ===
controls: 2/65 (0.031)
cohort: 5/79 (0.063) pval: 0.4575427461447079
pec: 3/14 (0.214) pval: 0.036569559687481004
sf: 3/9 (0.333) pval: 0.011362510494287447
nsf: 0/5 (0.000) pval: 1.0
eope: 0/1 (0.000) pval: 1.0
lope: 3/13 (0.231) pval: 0.03044096728307261
ghtn: 1/8 (0.125) pval: 0.2977040324136598

    group   n  count  proportion  odds_ratio    pvalue
0  cohort  79      5    0.063291    0.469841  0.457543
1     pec  14      3    0.214286    0.116402  0.036570
2      sf   9      3    0.333333    0.063492  0.011363
3     nsf   5      0    0.000000         inf  1.000000
4    eope   1      0    0.000000         inf  1.000000
5    lope  13      3    0.230769    0.105820  0.030441
6    ghtn   8      1    0.125000    0.222222  0.297704

In [16]:
nyu_md['chtn'] = nyu_md['Record ID'].str.lower().isin(nyu_chtn)

compare_binary_col(
    nyu_md=nyu_md,
    col='chtn',
    controls_ids=nyu_controls,
    group_ids={'cohort': nyu_ids,'pec':nyu_pec, 'sf':nyu_sf,'nsf':nyu_nsf,'eope':nyu_eope,'lope':nyu_lope,'ghtn':nyu_ghtn},
    id_col="Record ID"
)

=== chtn ===
controls: 3/65 (0.046)
cohort: 5/79 (0.063) pval: 0.7296034507388003
pec: 2/14 (0.143) pval: 0.21293682999212626
sf: 2/9 (0.222) pval: 0.10897893842134625
nsf: 0/5 (0.000) pval: 1.0
eope: 0/1 (0.000) pval: 1.0
lope: 2/13 (0.154) pval: 0.19182723393249773
ghtn: 0/8 (0.000) pval: 1.0

    group   n  count  proportion  odds_ratio    pvalue
0  cohort  79      5    0.063291    0.716129  0.729603
1     pec  14      2    0.142857    0.290323  0.212937
2      sf   9      2    0.222222    0.169355  0.108979
3     nsf   5      0    0.000000         inf  1.000000
4    eope   1      0    0.000000         inf  1.000000
5    lope  13      2    0.153846    0.266129  0.191827
6    ghtn   8      0    0.000000         inf  1.000000

In [17]:
compare_binary_col(
    nyu_md=nyu_md,
    col='Smoking Status ',
    controls_ids=nyu_controls,
    group_ids={'cohort': nyu_ids,'pec':nyu_pec, 'sf':nyu_sf,'nsf':nyu_nsf,'eope':nyu_eope,'lope':nyu_lope,'ghtn':nyu_ghtn},
    id_col="Record ID"
)

=== Smoking Status  ===
controls: 4/65 (0.062)
cohort: 8/79 (0.101) pval: 0.5473546889093649
pec: 4/14 (0.286) pval: 0.029577336364592345
sf: 2/9 (0.222) pval: 0.15283559444654674
nsf: 2/5 (0.400) pval: 0.05504794095090705
eope: 0/1 (0.000) pval: 1.0
lope: 4/13 (0.308) pval: 0.023200606498229293
ghtn: 0/8 (0.000) pval: 1.0

    group   n  count  proportion  odds_ratio    pvalue
0  cohort  79      8    0.101266    0.581967  0.547355
1     pec  14      4    0.285714    0.163934  0.029577
2      sf   9      2    0.222222    0.229508  0.152836
3     nsf   5      2    0.400000    0.098361  0.055048
4    eope   1      0    0.000000         inf  1.000000
5    lope  13      4    0.307692    0.147541  0.023201
6    ghtn   8      0    0.000000         inf  1.000000

In [18]:
compare_binary_col(
    nyu_md=nyu_md,
    col='Diabetes?',
    controls_ids=nyu_controls,
    group_ids={'cohort': nyu_ids,'pec':nyu_pec, 'sf':nyu_sf,'nsf':nyu_nsf,'eope':nyu_eope,'lope':nyu_lope,'ghtn':nyu_ghtn},
    id_col="Record ID"
)

=== Diabetes? ===
controls: 3/65 (0.046)
cohort: 3/79 (0.038) pval: 1.0
pec: 0/14 (0.000) pval: 1.0
sf: 0/9 (0.000) pval: 1.0
nsf: 0/5 (0.000) pval: 1.0
eope: 0/1 (0.000) pval: 1.0
lope: 0/13 (0.000) pval: 1.0
ghtn: 1/8 (0.125) pval: 0.3779664287092416

    group   n  count  proportion  odds_ratio    pvalue
0  cohort  79      3    0.037975    1.225806  1.000000
1     pec  14      0    0.000000         inf  1.000000
2      sf   9      0    0.000000         inf  1.000000
3     nsf   5      0    0.000000         inf  1.000000
4    eope   1      0    0.000000         inf  1.000000
5    lope  13      0    0.000000         inf  1.000000
6    ghtn   8      1    0.125000    0.338710  0.377966

In [19]:
compare_binary_col(
    nyu_md=nyu_md,
    col='IVF',
    controls_ids=nyu_controls,
    group_ids={'cohort': nyu_ids,'pec':nyu_pec, 'sf':nyu_sf,'nsf':nyu_nsf,'eope':nyu_eope,'lope':nyu_lope,'ghtn':nyu_ghtn},
    id_col="Record ID"
)

=== IVF ===
controls: 16/65 (0.246)
cohort: 18/79 (0.228) pval: 0.8451574521225796
pec: 2/14 (0.143) pval: 0.5040232460470786
sf: 2/9 (0.222) pval: 1.0
nsf: 0/5 (0.000) pval: 0.5819209991825184
eope: 0/1 (0.000) pval: 1.0
lope: 2/13 (0.154) pval: 0.7209853359171987
ghtn: 4/8 (0.500) pval: 0.2027880365846435

    group   n  count  proportion  odds_ratio    pvalue
0  cohort  79     18    0.227848    1.106576  0.845157
1     pec  14      2    0.142857    1.959184  0.504023
2      sf   9      2    0.222222    1.142857  1.000000
3     nsf   5      0    0.000000         inf  0.581921
4    eope   1      0    0.000000         inf  1.000000
5    lope  13      2    0.153846    1.795918  0.720985
6    ghtn   8      4    0.500000    0.326531  0.202788

In [20]:
compare_binary_col(
    nyu_md=nyu_md,
    col='Nulliparity?',
    controls_ids=nyu_controls,
    group_ids={'cohort': nyu_ids,'pec':nyu_pec, 'sf':nyu_sf,'nsf':nyu_nsf,'eope':nyu_eope,'lope':nyu_lope,'ghtn':nyu_ghtn},
    id_col="Record ID"
)

=== Nulliparity? ===
controls: 40/65 (0.615)
cohort: 51/79 (0.646) pval: 0.7312368437716523
pec: 11/14 (0.786) pval: 0.3566148889911351
sf: 6/9 (0.667) pval: 1.0
nsf: 5/5 (1.000) pval: 0.15237022777962492
eope: 1/1 (1.000) pval: 1.0
lope: 10/13 (0.769) pval: 0.3573858623690472
ghtn: 7/8 (0.875) pval: 0.24531957682730737

    group   n  count  proportion  odds_ratio    pvalue
0  cohort  79     51    0.645570    0.878431  0.731237
1     pec  14     11    0.785714    0.436364  0.356615
2      sf   9      6    0.666667    0.800000  1.000000
3     nsf   5      5    1.000000    0.000000  0.152370
4    eope   1      1    1.000000    0.000000  1.000000
5    lope  13     10    0.769231    0.480000  0.357386
6    ghtn   8      7    0.875000    0.228571  0.245320